# Generated by Django 3.2.8 on 2021-11-08 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('weekend_regular_tax', models.FloatField()),
                ('weekend_reward_tax', models.FloatField()),
                ('weekday_regular_tax', models.FloatField()),
                ('weekday_reward_tax', models.FloatField()),
            ],
        ),
    ]
